# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: mvn clean package
  displayName: 'Build the application'
- task: PublishBuildArtifacts@1
  inputs:
      PathtoPublish: 'target'
      ArtifactName: 'drop'
      publishLocation: 'Container'
- task: Docker@2
  inputs:   
    containerRegistry: '$(ContainerRegistry)'
    repository: '$(ContainerRegistry)/$(ContainerRegistryNamespace)/$(ContainerRegistryImageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.SourceBranchName)
      latest
